### ISSUE TITLE
Assimulo solvers

### ISSUE THREAD

**Issue by NikolaH1** [conda-forge/assimulo-feedstock#29] opened 2019-03-14 16:02 UTC
When I try to install assimulo withing conda environment I get the following error on the Python 3.6.8

Could not find cannot import name 'radau5'
Could not find cannot import name 'dopri5'
Could not find cannot import name 'rodas'
Could not find cannot import name 'odassl'
Could not find ODEPACK functions.
Could not find RADAR5
Could not find GLIMDA.

The assimulo is used for pyFMI simulations but unsucesfully. Why the solvers are not working

**Comment by jschueller** [comment] 2019-03-14 17:05
conda list ?

**Comment by NikolaH1** [comment] 2019-03-15 07:41
Installed here is the conda list:
assimulo                  3.0             py36h1fff9c8_1004    conda-forge

**Comment by jschueller** [comment] 2019-03-15 07:46
windows ?

**Comment by NikolaH1** [comment] 2019-03-15 07:49
Yes installed within anaconda

**Comment by jschueller** [comment] 2019-03-15 07:52
it's a duplicate of #19, closing

**Closed by jschueller** 2019-03-15 07:52 UTC
